#!/bin/sh
# Supervisor init.d script for Amazon Linux AMI.
#
# Originally forked from: https://gist.github.com/mhayes/866900
#
# chkconfig: 2345 80 20
# description: Bring up/down supervisord service.
# processname: supervisord

# Source function library.
. /etc/rc.d/init.d/functions

PATH=$PATH:/usr/local/bin

NAME="supervisord"
CONFIGFILE="/etc/$NAME.conf"
PIDFILE="/tmp/$NAME.pid"
SOCKETFILE="/tmp/supervisor.sock"

DAEMON=$(which $NAME 2>/dev/null)
[[ -z $DAEMON ]] && DAEMON="/usr/local/bin/$NAME"

SUPERVISORCTL=$(which supervisorctl 2>/dev/null)
[[ -z $SUPERVISORCTL ]] && SUPERVISORCTL="/usr/local/bin/supervisorctl"


if [[ ! -x $DAEMON ]]; then
    printf "$DAEMON: not found the command."
    exit 255
fi

if [[ ! -x $SUPERVISORCTL ]]; then
    printf "$SUPERVISORCTL: not found the command."
    exit 255
fi

start () {
    declare rc
    printf "Starting $NAME: "
    daemon "$DAEMON" -c "$CONFIGFILE"
    rc=$?
    printf "\n"
    return $rc
}

stop () {
    printf "Stopping $NAME: "
    $SUPERVISORCTL shutdown
    # make sure shutdown complete
    while [[ 1 ]]; do
        if [[ ! -f $PIDFILE && ! -S $SOCKETFILE ]]; then
            break
        fi
    done
}

usage () {
    printf "Usage: $0 {start|stop|status|restart}\n"
    exit 255
}

case "$1" in
    start) start ;;
    stop) stop ;;
    restart) stop; start ;;
    status) status "$DAEMON" ;;
    *) usage ;;
esac

exit
